### PR TITLE
Replace and play fix

### LINKED ISSUE #1808: Websocket replaceAndPlay fails when index is 0
When you pass the websocket interface replaceAndPlay using the list and index pragma. The call fails and the queue is left empty. Passing any other index succeeds.

`io.emit('replaceAndPlay',{list: [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}], index: 0})
`

I watched the logs (tail -f /var/log/volumio.log) and it seems that this request actually crashes the volumio service:
```
2019-09-23T20:44:36.528Z - info: CoreCommandRouter::volumioReplaceandPlayItems
2019-09-23T20:44:37.604Z - info: -------------------------------------------
2019-09-23T20:44:37.605Z - info: -----            Volumio2              ----
2019-09-23T20:44:37.605Z - info: -------------------------------------------
2019-09-23T20:44:37.606Z - info: -----          System startup          ----
2019-09-23T20:44:37.606Z - info: -------------------------------------------
2019-09-23T20:44:37.617Z - info: MYVOLUMIO Environment detected
2019-09-23T20:44:37.621Z - info: Plugin folders cleanup
2019-09-23T20:44:37.621Z - info: Scanning into folder /volumio/app/plugins/
```
(rest of boot process)

I know Javascript but I don't know much about debugging node environments, so I can't work out how to tell where the bug is.

### PR DESCRIPTION
**Pull request by gilphilbert**
Fixes #1808

Current code checks for the existence of data.index using:
```
} else if (data.list && data.index) {
```
Change to check for data.list!=undefined to avoid the situation where index.list=0 and the test fails when it should pass.

### CODE REVIEW

**Comment by xipmix** [comment]
There is a very similar check a few lines below
```
    } else if ((!(data.list && data.index) && data.item && data.item.uri)) {
        this.stateMachine.addQueueItems(data.item)
```
should that be changed as well ? I suppose the question is

**Comment by gilphilbert** [comment]
You're quite right - I've added a fix for that, too.

The crash seemed to be that the evaluation was false (since `if 0` evaluates to false) and this resulted in the wrong code being executed. The odd thing is that it should have been ending up here:
```
    } else {
        self.logger.error('Could not Replace and Play Item');
        defer.reject('Could not Replace and Play Item');
        }
```
...and there's no reason that should result in a crash.

**Comment by gilphilbert** [comment]
Ah, yes there is! `self` isn't defined as `var self = this;` is missing from the beginning of this function. Added that to the PR.

**Comment by xipmix** [comment]
Nice work. I wondered about the ```self``` thing, but missed the use of it in that ```else```.

**Comment by xipmix** [comment]
One last thing I was thinking about. We had this structure
```
if (condition1) {
} else if (condition2) {
} else if (! condtion2 and condition3 and condition4) {
}
```
why can't we say:
```
if (condition1) {
} else if (condition2) {
} else if (condition3 and condition4) {
  // condition2 cannot be true
}
```
The way you've expressed ```! condition2``` makes a lot of sense too, though.

**Comment by gilphilbert** [comment]
You are absolutely right - I was focusing on the smaller picture. There's no way to get to that line if those statements are true, so they're simply not required. I'm not sure why they were there, perhaps before lists of tracks were supported? Anyway, removed the extra evals  to make it more readable.

Thanks for checking over my code!

**Comment by volumio** [comment]
Thanks!

**Pull request merged**
