### PR TITLE
Allow addPlay to specify index

### PR DESCRIPTION
**Pull request by gilphilbert**
Enhance addPlay to allow the selection of a track index. Used as:

`io.emit('addPlay ', { list: [ { "uri" : "..." }, { "uri" : "..." } ], index: 1 });

Would add two tracks to the queue and play the second track.

### CODE REVIEW

**Comment by xipmix** [comment]
A couple of questions/comments:
*  this would be clearer
```
                  if (data.index != undefined) {
                      index=data.index;
                  }
```
or even 
```if (data.index != undefined) index=data.index;```

* Missing ```;``` on this line?
```self.commandRouter.addQueueItems(tracks)```
* too much Indentation on the line below?

**Comment by gilphilbert** [comment]
Thanks xipmix. This was taken from my dev machine, surprised it works with the missing semicolon - I missed that.

I've corrected the whitespace (as well as updating for 4-space indenting to match the rest of the file) and changed the if statement to include braces.

**Comment by xipmix** [comment]
This is indeed conflicting, I tried a test merge with 2488f384538546350daead0ec9c4ab706450c79a. It would be nice if github flagged such PRs  in the summary list, I thought it used to do that. Do authors get a ping from github when their PR starts to conflict? I guess not.

Care to respin? Also I'm not clear how the variable ```e``` gets initialised now.

**Comment by gilphilbert** [comment]
Will respin, closing this PR

**Pull request closed without merging**
