### PR TITLE
More logsubmit work

### PR DESCRIPTION
**Pull request by xipmix**
The fix I submitted a few days ago did not handle an important case - single quotes in the description. I've fixed that now, in the same way as we did in networkfs. The fix has been tested, see eg pBwpQAT.

While I was there I noticed the catch() clauses were using what seemed to be the wrong name for the error object.

Finally as described in #1237 I found it may be useful to clean up the data sent to socket.on('pushSendBugReport` before trying to parse it into json.

Comments and further testing welcome. Tested on 2.201 plus these patches.

### CODE REVIEW

**Comment by volumio** [comment]
Well done!

**Comment by volumio** [comment]
@xipmix we still have passwords exposed for NAS mounts... I think we should fix this asap... any idea?

**Comment by xipmix** [comment]
can you point me to or send an example, I am happy to add further checks

**Comment by volumio** [comment]
You can try adding a NAS drive with fake user and password credentials, and then submit logs. They are exposed on the mount command

**Comment by xipmix** [comment]
Thanks, it's late here... I pushed an extra commit to this PR. Is that ok or should I submit separately?

**Comment by volumio** [comment]
Yes do it separately, I'll look at logsubmit3

**Comment by xipmix** [comment]
It's going to be a little while. There is something up with the behaviour on the command line vs within logsubmit.js. The current logsubmit3 branch I have removes everything after ```/bin/``` on the offending line.

**Pull request merged**
