### PR TITLE
Use git submodule for UI

### PR DESCRIPTION
**Pull request by jomo**
I couldn't test this because I don't have access to the Volumio2-UI repo, but I'm fairly sure this should work.

To make this work, you'll need to run this in the UI repo:
```shell
git-subtree split --prefix dist -b dist
git checkout dist
git push origin dist
```
That will automatically create a new branch based on the dist/ directory.
The new branch will be called dist.
Push that branch to GitHub.

When that is done, check out this PR and run
```shell
git submodule init
git submodule update --remote
```

After that you should have the UI's dist folder (technically branch) at http/www.
To update the UI in future, update the dist branch using the subtree command and update the submodule in this repo.

### CODE REVIEW

**Comment by volumio** [comment]
Great idea, don't know if this will work. However I'll give you access to UI repo, want to try?

**Comment by jomo** [comment]
sure

**Comment by jomo** [comment]
works!
```shell
$ ls http/www
app/
assets/
scripts/
styles/
favicon.ico
index.html
```

---

I guess we can merge?

**Comment by volumio** [comment]
Great work! Really handy!

**Comment by jomo** [comment]
:+1:

**Comment by volumio** [comment]
Great, now we could automate this via a script in the package.json

**Comment by jomo** [comment]
done!

**Comment by volumio** [comment]
now we talk!

**Comment by jomo** [comment]
FYI https://github.com/volumio/Volumio2-UI/blob/9132d73db73b587e551dfcfc2a721e0a019db4ca/README.md

**Comment by volumio** [comment]
Yes that was needed...

**Pull request merged**
