### PR TITLE
Update dacs.json

### PR DESCRIPTION
**Pull request by miquel83blauw**

### CODE REVIEW

**Comment by volumio** [comment]
Hi Miquel, to make it work we will need to include the modules and overlays on the image. 
Could you do a PR for it as well? 
Look at what we've done for Allo's hardware 
https://github.com/volumio/Build/blob/a6d7cd4768517e14ef91b197ccf8fa729981f2ad/scripts/raspberryconfig.sh#L162-L177

**Comment by miquel83blauw** [comment]
Dear,

I'm trying to add the modules and overlays, but cannot find out how to PR it. Sorry for my bad software knowledge, I'm a hardware developer.

https://github.com/miquel83blauw/dionaudio-loco/blob/master/dionaudio-loco-overlay.dts
https://github.com/miquel83blauw/dionaudio-loco/blob/master/dionaudio_loco.c

https://github.com/miquel83blauw/dionaudio-loco-v2/blob/master/dionaudio-loco-v2-overlay.dts
https://github.com/miquel83blauw/dionaudio-loco-v2/blob/master/dionaudio_loco-v2.c

**Comment by volumio** [comment]
Hi Miquel,
no problem. Just send me the compiled modules for current Volumio kernel, and dt-overlays and I'll add them

**Comment by miquel83blauw** [comment]
Hi,
Ok, the modules are not compiled for the Volumio kernel yet. I first have to find out how to do that..

**Comment by volumio** [comment]
Ok, you might find useful to look here:
https://volumio.org/forum/kernel-header-files-t5146.html

**Comment by miquel83blauw** [comment]
Hi,

I have tried to complie the modules on the Raspberry Pi with the latest volumio kernel, but this is to hard for me, a lot of errors... I have to find someone who can help me with compiling these modules for volumio.

**Pull request closed without merging**
