### PR TITLE
Partial Swedish translation

### PR DESCRIPTION
**Pull request by ordtrogen**
Submitting this partial translation because I will not have time to work on it for about a week and would like for my repository not to diverge too much from the master branch.

### CODE REVIEW

**Comment by volumio** [comment]
Ok, so I will wait for the complete translation?

**Comment by ordtrogen** [comment]
Sorry if I was unclear. If possible, please merge now and I will submit more later on.

**Comment by volumio** [comment]
Ok, thanks. Please also, if you can, translate the UI one ?
https://github.com/volumio/Volumio2-UI/blob/master/src/app/i18n/locale-sv.json

**Comment by ordtrogen** [comment]
Certainly. My aim is to provide a complete translation of Volumio. First I'll complete this one, and then I'll go on to Volumio2-UI

TBH, although I've read what I could find, I'm not sure I understand how the two parts of the software relate (Volumio2 vs. Volumio2-UI)

**Comment by volumio** [comment]
Thanks!
This is the backend (the thing that handles all the background operations), the UI is the user interface. 
They are 2 different pieces of software that work together

**Comment by ordtrogen** [comment]
Yeah, that's what I'd read. I guess what I don't understand is why there are localizable strings in the backend.

**Pull request merged**
