### PR TITLE
Add "path" variable for mounts and other fixes for cifs and nfs mounts

### PR DESCRIPTION
**Pull request by mpasteur**
many changes to add a name to mounted path. Fixes for nfs and cifs with authentication
see #104 
Some changes in another commit on Volumio UI to add additional fields

Caution : nfs with authentication is not allowed at the moment....

### CODE REVIEW

**Comment by volumio** [comment]
Thanks!!! I'll test and merge! Agree with you that this add way more clarity..

**Comment by volumio** [comment]
Unfortunately on my setup that doesn't work...

My music is @ 192.168.1.142/Flac

inputting:
name: Flac
Path: Flac
IP: 192.168.1.142

And I don't get any alert..

**Comment by mpasteur** [comment]
cifs or nfs ?

is your config correctly saved in config.json ?

**Comment by volumio** [comment]
cifs... I'm diggin into that..
The conf gets saved, and the system reports as not mounted (the folder is created with the right name but its empty)

**Comment by mpasteur** [comment]
ok don't know if it's the same bug as yours but it seems there is a problem
with "add a new drive"
If i add i get one message
info: [1452542003814] Error Mounting Share synomms: exec error Error:
Command failed: /bin/sh -c /usr/bin/sudo /bin/mount -t cifs -o
username=,password=,dir_mode=0777,file_mode=0666,iocharset=utf8
//synomms/music/mp3 /mnt/NAS/synomms
username specified with no parameter

username and password are empty but should be "guest" ( mount -t cifs -o
guest,dir_mode=0777,file_mode=0666,iocharset=utf8 //192.168.0.10/music/mp3
/mnt/NAS/synomms)

if i return to home , then come back to "My Music" and make an edit it's ok.

**Comment by mpasteur** [comment]
i've made another PR see #146

**Pull request closed without merging**
