### PR TITLE
allow whitespaces in plugin path- and filenames when packaged

### PR DESCRIPTION
**Pull request by rpi-Receiver**

### CODE REVIEW

**Comment by volumio** [comment]
It should not have whitespaces but rather _

**Comment by rpi-Receiver** [comment]
Wanted to add Remote Controls to https://github.com/volumio/volumio-plugins/tree/master/plugins/accessory/ir_controller -> lots of whitespaces

**Comment by volumio** [comment]
Sorry, I don't see any... What did you want to add? I can help...

**Comment by rpi-Receiver** [comment]
in the configurations directory

**Comment by rpi-Receiver** [comment]
Of course I can reopen - New to github....

**Comment by volumio** [comment]
Let me test it and I'll eventually merge

**Comment by volumio** [comment]
It works as expected, thanks

**Pull request merged**
