### PR TITLE
Remove deprecated `node-uuid` module in favour of `uuid`

### PR DESCRIPTION
**Pull request by ashthespy**
Small steps with the deprecated packages.

We have quite some outdated packages, some of which might prudent to update..
```
found 19 vulnerabilities (13 low, 5 high, 1 critical) in 1082 scanned packages
  13 vulnerabilities require semver-major dependency updates.
  6 vulnerabilities require manual review. See the full report for details.
```

### CODE REVIEW

**Comment by volumio** [comment]
@ashthespy looks good, need to rebuild node modules before merging

**Comment by ashthespy** [comment]
Then lets wait for a few more fixes before triggering a build?

**Comment by volumio** [comment]
@ashthespy yes. I am looking at remving inotify as well

**Comment by ashthespy** [comment]
Changed branch to `buster/dev`, merging it in there so we can stage more updates there..

**Comment by ashthespy** [comment]
@volumio Can this be merged? There are more modules that can be cleandup..

**Comment by volumio** [comment]
Done. Now I think:
- We merge Tim PR also here
- We rebuild modules 
- We merge into master
- We do new builds
Do you agree?

**Comment by ashthespy** [comment]
Sound good! 👍

**Pull request merged**
