### PR TITLE
Better Optimised Backgrounds

### PR DESCRIPTION
**Pull request by apinner**
Spent a bit of time trying to better optimise the background images to
help with https://github.com/volumio/Volumio2/issues/599

Reduced by 5MB in total, less than half of their original size.

### CODE REVIEW

**Comment by heis2201** [comment]
How about having those background images as a totally optional thing. Users with plenty of RAM can use them, others on Rpi1 with only 512MB may just not use them. They are eyecandy, not an essential function.

**Comment by apinner** [comment]
Do you really dislike our UI, you seem to want to remove all of it!? ;)

Nothing wrong with some eyecandy, we want volumio to look good! We will rework the backgrounds so they are optional.

@volumio as an idea, why don't we host the images and only include a thumbnail. Then when the user selects a background it downloads it behind the scenes?

**Comment by heis2201** [comment]
@apinner No, don't get me wrong. I love the UI. I am just teasing you to first put effort on functionality and then on the eyecandy. 

I really appreciate all the effort that is put into the project by the team behind Volumio. A million thanks!

Does the standard volumio install come with a swapfile enabled? That could be an option for those devices with limited RAM, even though is slows down the OS, it wouldn't crash...

**Comment by apinner** [comment]
Trouble using a swap on the SD card is you increase the read/writes and wear out the card. Volumio is designed to run entirely in RAM for that reason.

**Comment by heis2201** [comment]
I can maybe manually create swap file on an (old) external 1gb usb thumb drive, where I don't care if it breaks... plug in the next one..

**Comment by volumio** [comment]
Thanks alex!

**Pull request merged**
