### PR TITLE
Bugfix playlist stops

### PR DESCRIPTION
**Pull request by michaelpeeters**
The fix addresses 2 issues:
- support negative "remainingTime": https://volumio.org/forum/possible-bug-statemachine-increaseplaybacktimer-t11921.html.
- sometimes, the 500ms setTimeout call to increasePlaybackTimer gets called AFTER the feedback from the mpd daemon is processed. This gives a mismatch between the currentPosition and the "syncstate" that is sent to the webclients over websockets.
    It appears that the nodejs event loop priority is causing this on slower / older devices? https://stackoverflow.com/questions/23269153/priority-between-settimeout-and-setimmediate?rq=1

details:
- volumio#1745. https://github.com/volumio/Volumio2/issues/1745
- https://forum.volumio.org/play-stops-midway-through-queue-since-444-t11180-10.html

### CODE REVIEW

**Comment by volumio** [comment]
Brilliant! Well done!

**Comment by kermitnc** [comment]
I patched my statemachine to and there is still an issue with mixed playlist (e.g. a webradio entry following a TIDAL entry) when the system tries to prefetch the webradio while playback. 
Sometime it can recover in seconds and sometimes not.

**Comment by xipmix** [comment]
@kermitnc could you please open a new issue for this?
It would also help to post a log file showing what is logged when this happens.

**Comment by kermitnc** [comment]
sure I can.

track0 is a tidal track, and title1 is webradio (rockantenne):

volumio.log:

> 2019-08-25T14:33:25.221Z - info: CorePlayQueue::getTrack 0
2019-08-25T14:33:25.222Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:30.229Z - info: ERROR increasePlaybackTimer remainingTime:-157 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.229Z - info: ERROR increasePlaybackTimer remainingTime:-157 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.230Z - info: ERROR increasePlaybackTimer remainingTime:-158 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.230Z - info: ERROR increasePlaybackTimer remainingTime:-158 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.230Z - info: ERROR increasePlaybackTimer remainingTime:-158 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.480Z - info: ERROR increasePlaybackTimer remainingTime:-408 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.481Z - info: ERROR increasePlaybackTimer remainingTime:-408 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.483Z - info: ERROR increasePlaybackTimer remainingTime:-410 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.484Z - info: ERROR increasePlaybackTimer remainingTime:-411 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.484Z - info: ERROR increasePlaybackTimer remainingTime:-412 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.730Z - info: ERROR increasePlaybackTimer remainingTime:-658 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.731Z - info: ERROR increasePlaybackTimer remainingTime:-659 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.733Z - info: ERROR increasePlaybackTimer remainingTime:-661 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.734Z - info: ERROR increasePlaybackTimer remainingTime:-662 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.735Z - info: ERROR increasePlaybackTimer remainingTime:-662 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.981Z - info: ERROR increasePlaybackTimer remainingTime:-909 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.982Z - info: ERROR increasePlaybackTimer remainingTime:-910 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.984Z - info: ERROR increasePlaybackTimer remainingTime:-911 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.985Z - info: ERROR increasePlaybackTimer remainingTime:-912 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:30.985Z - info: ERROR increasePlaybackTimer remainingTime:-913 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.232Z - info: ERROR increasePlaybackTimer remainingTime:-1160 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.233Z - info: ERROR increasePlaybackTimer remainingTime:-1161 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.235Z - info: ERROR increasePlaybackTimer remainingTime:-1163 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.236Z - info: ERROR increasePlaybackTimer remainingTime:-1163 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.236Z - info: ERROR increasePlaybackTimer remainingTime:-1164 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.482Z - info: ERROR increasePlaybackTimer remainingTime:-1410 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.483Z - info: ERROR increasePlaybackTimer remainingTime:-1411 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.486Z - info: ERROR increasePlaybackTimer remainingTime:-1413 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.486Z - info: ERROR increasePlaybackTimer remainingTime:-1414 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.487Z - info: ERROR increasePlaybackTimer remainingTime:-1414 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.733Z - info: ERROR increasePlaybackTimer remainingTime:-1660 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.734Z - info: ERROR increasePlaybackTimer remainingTime:-1661 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.737Z - info: ERROR increasePlaybackTimer remainingTime:-1664 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.738Z - info: ERROR increasePlaybackTimer remainingTime:-1665 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.738Z - info: ERROR increasePlaybackTimer remainingTime:-1665 negative - askedForPrefetch:true - simulateStopStartDone:false
2019-08-25T14:33:31.845Z - info: 
---------------------------- MPD announces state update: player
2019-08-25T14:33:31.846Z - info: ControllerMpd::getState
2019-08-25T14:33:31.847Z - info: ControllerMpd::sendMpdCommand status
2019-08-25T14:33:31.847Z - info: sending command...
2019-08-25T14:33:31.849Z - info: parsing response...
2019-08-25T14:33:31.850Z - info: ControllerMpd::parseState
2019-08-25T14:33:31.850Z - info: ControllerMpd::pushState
2019-08-25T14:33:31.851Z - info: CoreCommandRouter::servicePushState
2019-08-25T14:33:31.851Z - info: CoreStateMachine::syncState
2019-08-25T14:33:31.851Z - info: CoreStateMachine::pushState
2019-08-25T14:33:31.851Z - info: CoreStateMachine::getState
2019-08-25T14:33:31.851Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:31.851Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:31.891Z - info: CorePlayQueue::getTrack 0
2019-08-25T14:33:31.891Z - info: STATE SERVICE {"status":"stop","position":null,"seek":null,"duration":null,"samplerate":null,"bitdepth":null,"channels":null,"random":false,"updatedb":false,"repeat":false,"isStreaming":false,"title":null,"artist":null,"album":null,"uri":null}
2019-08-25T14:33:31.891Z - info: CURRENT POSITION 0
2019-08-25T14:33:31.891Z - info: CoreStateMachine::syncState   stateService stop
2019-08-25T14:33:31.891Z - info: CoreStateMachine::syncState   currentStatus play
2019-08-25T14:33:31.891Z - info: CURRENT POSITION 0
2019-08-25T14:33:31.891Z - info: CURRENT POSITION 1
2019-08-25T14:33:31.892Z - info: CoreStateMachine::play index undefined
2019-08-25T14:33:31.892Z - info: CoreStateMachine::setConsumeUpdateService undefined
2019-08-25T14:33:31.892Z - info: CoreStateMachine::pushState
2019-08-25T14:33:31.892Z - info: CoreStateMachine::getState
2019-08-25T14:33:31.892Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:31.892Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:31.892Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:31.950Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:31.951Z - info: CoreStateMachine::startPlaybackTimer
2019-08-25T14:33:31.951Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:31.951Z - info: [1566743611951] ControllerWebradio::clearAddPlayTrack
2019-08-25T14:33:31.952Z - info: ControllerMpd::sendMpdCommand stop
2019-08-25T14:33:31.954Z - info: ------------------------------ 108ms
2019-08-25T14:33:31.960Z - info: sending command...
2019-08-25T14:33:31.961Z - info: CoreStateMachine::pushState
2019-08-25T14:33:31.961Z - info: CoreStateMachine::getState
2019-08-25T14:33:31.961Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:31.961Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:31.962Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:32.012Z - info: parsing response...
2019-08-25T14:33:32.012Z - info: ControllerMpd::sendMpdCommand clear
2019-08-25T14:33:32.012Z - info: sending command...
2019-08-25T14:33:32.166Z - info: 
---------------------------- MPD announces system playlist update
2019-08-25T14:33:32.166Z - info: Ignoring MPD Status Update
2019-08-25T14:33:32.167Z - info: parsing response...
2019-08-25T14:33:32.167Z - info: ControllerMpd::sendMpdCommand load "http://yp.shoutcast.com/sbin/tunein-station.m3u?id=500181"
2019-08-25T14:33:32.167Z - info: sending command...
2019-08-25T14:33:32.255Z - info: 
2019-08-25T14:33:32.257Z - info: 
---------------------------- MPD announces system playlist update
2019-08-25T14:33:32.257Z - info: Ignoring MPD Status Update
2019-08-25T14:33:32.258Z - info: ------------------------------ 92ms
2019-08-25T14:33:32.258Z - info: parsing response...
2019-08-25T14:33:32.259Z - info: CoreStateMachine::setConsumeUpdateService mpd
2019-08-25T14:33:32.259Z - info: ControllerMpd::sendMpdCommand play
2019-08-25T14:33:32.260Z - info: sending command...
2019-08-25T14:33:32.262Z - info: ------------------------------ 5ms
2019-08-25T14:33:32.262Z - info: parsing response...
2019-08-25T14:33:33.284Z - info: 
---------------------------- MPD announces state update: player
2019-08-25T14:33:33.286Z - info: ControllerMpd::getState
2019-08-25T14:33:33.286Z - info: ControllerMpd::sendMpdCommand status
2019-08-25T14:33:33.286Z - info: sending command...
2019-08-25T14:33:33.287Z - info: 
---------------------------- MPD announces state update: player
2019-08-25T14:33:33.288Z - info: ControllerMpd::getState
2019-08-25T14:33:33.288Z - info: ControllerMpd::sendMpdCommand status
2019-08-25T14:33:33.288Z - info: sending command...
2019-08-25T14:33:33.290Z - info: 
---------------------------- MPD announces system playlist update
2019-08-25T14:33:33.291Z - info: Ignoring MPD Status Update
2019-08-25T14:33:33.292Z - info: 
---------------------------- MPD announces state update: player
2019-08-25T14:33:33.292Z - info: parsing response...
2019-08-25T14:33:33.292Z - info: ControllerMpd::getState
2019-08-25T14:33:33.292Z - info: ControllerMpd::sendMpdCommand status
2019-08-25T14:33:33.293Z - info: parsing response...
2019-08-25T14:33:33.293Z - info: ControllerMpd::parseState
2019-08-25T14:33:33.293Z - info: ControllerMpd::sendMpdCommand playlistinfo
2019-08-25T14:33:33.294Z - info: sending command...
2019-08-25T14:33:33.295Z - info: ControllerMpd::parseState
2019-08-25T14:33:33.295Z - info: ControllerMpd::sendMpdCommand playlistinfo
2019-08-25T14:33:33.295Z - info: sending command...
2019-08-25T14:33:33.296Z - info: sending command...
2019-08-25T14:33:33.300Z - info: ------------------------------ 10ms
2019-08-25T14:33:33.300Z - info: parsing response...
2019-08-25T14:33:33.301Z - info: parsing response...
2019-08-25T14:33:33.301Z - info: parsing response...
2019-08-25T14:33:33.301Z - info: ControllerMpd::parseState
2019-08-25T14:33:33.302Z - info: ControllerMpd::sendMpdCommand playlistinfo
2019-08-25T14:33:33.302Z - info: ControllerMpd::parseTrackInfo
2019-08-25T14:33:33.302Z - info: ControllerMpd::parseTrackInfo
2019-08-25T14:33:33.303Z - info: sending command...
2019-08-25T14:33:33.303Z - info: ControllerMpd::pushState
2019-08-25T14:33:33.304Z - info: CoreCommandRouter::servicePushState
2019-08-25T14:33:33.304Z - info: CoreStateMachine::syncState
2019-08-25T14:33:33.304Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:33.304Z - info: STATE SERVICE {"status":"play","position":0,"seek":325,"duration":0,"samplerate":"44.1 kHz","bitdepth":"24 bit","channels":2,"random":false,"updatedb":false,"repeat":false,"isStreaming":false,"title":"Phil Collins - In the air tonight","artist":"ROCK ANTENNE","album":null,"uri":"http://mp3channels.webradio.antenne.de:80/rockantenne","trackType":""}
2019-08-25T14:33:33.304Z - info: CURRENT POSITION 1
2019-08-25T14:33:33.305Z - info: CoreStateMachine::syncState   stateService play
2019-08-25T14:33:33.305Z - info: CoreStateMachine::syncState   currentStatus stop
2019-08-25T14:33:33.305Z - info: CoreStateMachine::pushState
2019-08-25T14:33:33.305Z - info: CoreStateMachine::getState
2019-08-25T14:33:33.305Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:33.306Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:33.373Z - info: ControllerMpd::pushState
2019-08-25T14:33:33.373Z - info: CoreCommandRouter::servicePushState
2019-08-25T14:33:33.373Z - info: CoreStateMachine::syncState
2019-08-25T14:33:33.373Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:33.374Z - info: STATE SERVICE {"status":"play","position":0,"seek":487,"duration":0,"samplerate":"44.1 kHz","bitdepth":"24 bit","channels":2,"random":false,"updatedb":false,"repeat":false,"isStreaming":false,"title":"Phil Collins - In the air tonight","artist":"ROCK ANTENNE","album":null,"uri":"http://mp3channels.webradio.antenne.de:80/rockantenne","trackType":""}
2019-08-25T14:33:33.374Z - info: CURRENT POSITION 1
2019-08-25T14:33:33.374Z - info: CoreStateMachine::syncState   stateService play
2019-08-25T14:33:33.374Z - info: CoreStateMachine::syncState   currentStatus play
2019-08-25T14:33:33.374Z - info: Received an update from plugin. extracting info from payload
2019-08-25T14:33:33.375Z - info: CoreCommandRouter::executeOnPlugin: albumart , getAlbumArt
2019-08-25T14:33:33.375Z - info: CoreStateMachine::pushState
2019-08-25T14:33:33.375Z - info: CoreStateMachine::getState
2019-08-25T14:33:33.375Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:33.375Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:33.411Z - info: CoreStateMachine::pushState
2019-08-25T14:33:33.411Z - info: CoreStateMachine::getState
2019-08-25T14:33:33.411Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:33.411Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:33.473Z - info: ------------------------------ 188ms
2019-08-25T14:33:33.474Z - info: ------------------------------ 187ms
2019-08-25T14:33:33.478Z - info: parsing response...
2019-08-25T14:33:33.478Z - info: ControllerMpd::parseTrackInfo
2019-08-25T14:33:33.479Z - info: ControllerMpd::pushState
2019-08-25T14:33:33.479Z - info: CoreCommandRouter::servicePushState
2019-08-25T14:33:33.479Z - info: CoreStateMachine::syncState
2019-08-25T14:33:33.479Z - info: CorePlayQueue::getTrack 1
2019-08-25T14:33:33.479Z - info: STATE SERVICE {"status":"play","position":0,"seek":487,"duration":0,"samplerate":"44.1 kHz","bitdepth":"24 bit","channels":2,"random":false,"updatedb":false,"repeat":false,"isStreaming":false,"title":"Phil Collins - In the air tonight","artist":"ROCK ANTENNE","album":null,"uri":"http://mp3channels.webradio.antenne.de:80/rockantenne","trackType":""}
2019-08-25T14:33:33.480Z - info: CURRENT POSITION 1
2019-08-25T14:33:33.480Z - info: CoreStateMachine::syncState   stateService play
2019-08-25T14:33:33.480Z - info: CoreStateMachine::syncState   currentStatus play
2019-08-25T14:33:33.480Z - info: Received an update from plugin. extracting info from payload
2019-08-25T14:33:33.480Z - info: CoreCommandRouter::executeOnPlugin: albumart , getAlbumArt
2019-08-25T14:33:33.481Z - info: CoreStateMachine::pushState
2019-08-25T14:33:33.481Z - info: CoreStateMachine::getState
2019-08-25T14:33:33.481Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:33.481Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:33.519Z - info: CoreStateMachine::pushState
2019-08-25T14:33:33.519Z - info: CoreStateMachine::getState
2019-08-25T14:33:33.519Z - info: CoreCommandRouter::volumioPushState
2019-08-25T14:33:33.519Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
2019-08-25T14:33:33.568Z - info: ------------------------------ 276ms

In this case, the player recovered but in some cases it does not.

**Pull request merged**
