### PR TITLE
fixed typo ("accross")

### PR DESCRIPTION
**Pull request by bablat**
Just a simple typo

### CODE REVIEW

**Comment by volumio** [comment]
Sure? That does not sound quite right to me, but I'm not english native..

**Comment by bablat** [comment]
Neither am I, but the "accross" is incorrect, "across" is the correct spelling.
The alternative wording sounds more accurate to me, and the words are properly spelled. Feel free to reject and simply change to "across".

I'll review the rest of the strings and offer a few other changes.

**Comment by volumio** [comment]
Thanks! Maybe we could hear what @apinner thinks, since he's properly english!

**Comment by bablat** [comment]
@volumio, this should be reopened and merged, this edit is not included in #1052.

**Comment by volumio** [comment]
I opted to just change across. Thanks!

**Comment by chsims1** [comment]
As a native English speaker ;) the alternative text is the "better" English, but the meaning is still clear with "across"

**Comment by volumio** [comment]
Proper english 1 : Michelangelo 0 
lol, merged

**Pull request merged**
