### PR TITLE
Set up consistant codestyle

### PR DESCRIPTION
**Pull request by ashthespy**
Further to #1612 

### Workflow 
First install the dependencies with `npm install --only=dev` or more specifically:
   ```shell
   > npm i husky@next lint-staged prettier semistandard
   ```
All further commits will be automatically formatted using the `semistandard` style  and will prompt you to adhere to the styleguide. 
We could then fix all lint errors in the file when you make some changes, rather than attempt to fix the entire repo in one go.  
Of course you can always pass the `--no-verify` flag to git if you don't feel inclined to fix all the lint errors, and just use the formatting.  

Also included sample of the formatting for the parent dir. I started fixing all the lint errors, but soon got bored. :-}

If this works, can run the formatting for the entire repo in oneshot.

### CODE REVIEW

**Comment by volumio** [comment]
Great, one thing: can we just remove prettier? I find it rather annoying, especially when it breaks lines. What do you think?

**Comment by ashthespy** [comment]
I guess so, the main thing that prettier brings to the table is wrapping of long lines, but it looks to be quite aggressive at it.

**Comment by volumio** [comment]
Ok, so can you remove prettier and redo the PR? The code has been reformatted with prettier so I guess you can just stash it and I will take care of initial formatting

**Comment by ashthespy** [comment]
Will rework and force push in a bit..

**Comment by ashthespy** [comment]
Done - also ran `--fix  *.js` for  `__dirname`. 
Did not fix the errors the linter warns about, I'd propose we fix the formatting in one commit, and the linting in another?

**Comment by volumio** [comment]
Great! It looks really really nice!

**Comment by ashthespy** [comment]
In the near future (once all errors are also fixedup), we can set up travis to complain if any PR's/commits don't match this style..

**Comment by sstark** [comment]
Is there a document somewhere that explains the official volumio coding style?

**Comment by ashthespy** [comment]
From #1612 [`semistandard`](https://github.com/Flet/semistandard) style was settled upon. It is [`standardjs`](https://standardjs.com/) but with semicolons. 

PS: Relevant kxcd https://xkcd.com/927/

!xkcd

**Comment by sstark** [comment]
Thanks, found it on the standardjs link. I wanted something I can read and learn and then lint later. There is no mentioning of tabs vs. spaces. I don't care which, but maybe there is a standard for the project?

**Comment by ashthespy** [comment]
Hmm, https://standardjs.com/rules.html - first rule ;-)
What editor/IDE do you use? You should find an appropriate package/plugin for it at [`semistandard`](https://github.com/Flet/semistandard#editor-plugins) readme page.

**Comment by sstark** [comment]
Hm, I just clicked that first links, searched for "tabs" and found: "just pick something" :) Anyway, that's good. I use vim which has all the plugins needed, but am completely new to js and when making a patch for the ampswitch plugin I found completely messed up code that I want to fix.

**Comment by ashthespy** [comment]
FWIW - the idea behind picking this is that you don't have to focus on setting this all up manually, and just use the inbuilt npm package `semistandard`. But I do understand that if you don't have a `nodejs` installation then it a bit much to install `nodejs` just to lint ;-)

FWIW (II) - The plugin repo doesn't currently have any style guide - I think when I last edited `ampswitch` I just used atom's Js formatter

**Pull request merged**
