### PR TITLE
Properly escape double quotes when constructing mpd command strings - respin

### PR DESCRIPTION
**Pull request by xipmix**
This replaces PR #1455. See also Issues #1454 and #1430

### CODE REVIEW

**Comment by xipmix** [comment]
I doubt I have any credibility with the community. 

I appreciate you are short of review time. Can you briefly outline what your test process would be (so others can reproduce it)?
The tests I did are described in #1482, if people can do something like that would that be sufficient?

Hmm. What if we add something to /usr/local/bin/volumio.sh that allows someone to pull a PR into their volumio, and then revert the change when they are done? The PR submitters would need to give some notes on what they want people to check.

**Comment by volumio** [comment]
Credibility is something you build with your work, and you have plenty of credit to be credible.

I usually play my tracks for a whole day and try to crash the thing.

Imho it would be wiser to give the exact commands as of now, and then ask to submit result. Once done its sufficient to delete user data. 

But we could set up a way to test PRs as you ask, it would be super useful

**Comment by xipmix** [comment]
> Imho it would be wiser to give the exact commands as of now, and then ask to submit result. Once done its sufficient to delete user data.

had trouble parsing that - I take it you mean 'give the exact commands for people to do the test with', and then they should put comments on the result in the PR ? A test script that produces a pasteable log perhaps?

I'll look into the 'prtest' idea a bit more.

**Comment by volumio** [comment]
I would go with just a forum post with the instructions and list of command to test

**Comment by chsims1** [comment]
I'm very happy to do tests, as long as it's spelled out exactly how and what you want doing.  As for credibility, I think you are doing a wonderful job xipmix ;)

I think the forum post idea is the simplest way forward to involve more testers .... if you don't want to post on forum, then put the info here & I'll post it for you.

**Comment by xipmix** [comment]
@chsims1 Thanks for the kind words. How about trying this yourself and if it works others could try. I'm happy for you to post to the forum. We probably only need a few positive results.

What the patch is trying to do is improve the handling of albums that have double quote marks (") in their names. If you have an album like that in your collection it will probably not show up when browsing albums; this patch intends to fix that.

To test the patch,
1. Attached is a small shell script [test.txt](https://github.com/volumio/Volumio2/files/1739581/test.txt)  . Save it and upload into your volumio
```
$ scp test.txt volumo@volumio:test.sh
```
2. Run the script to apply the patch, and restart volumio
```
volumio@volumio$ sh test.sh
Patch applied successfully. Please restart volumio
To undo the patch:  cd /volumio; git reset --hard
volumio@volumio$ sudo systemctl restart volumio
```
3. Browse your albums to check if the missing albums appear.

To report results,
1. Please give your system version
```
volumo@volumio$ cat /etc/os-release
```
2. If the patch failed to apply, please report what was printed out.
3. Please report any changes you noticed when browsing your albums, particularly if items with " in the name appeared.

**Comment by chsims1** [comment]
OK, might not be able to try until the weekend ... will see how things go.

**Comment by xipmix** [comment]
Ok thanks for taking the time to try this. It doesn't look like a feasible approach - it seems it would require rebasing the patches to the last revision that went into the release you are running. That could be done, but then we are no longer testing the thing @volumio needs us to test, that merging into the current master (e89dda7f2d3f5b8120b2923126c4acde2f9d395e Fix plugin uninstall, update and unzip) will work and not break anything.

**Comment by chsims1** [comment]
OTA update to 2.368 and patch is now applied.

I have always removed double quotes from my music files as a matter of course, so for this test I introduced them into one track file name and the folder name holding the track.

1. Before patch.

Track filename with quotes: I can see the track but I can't play it.
Folder name with quotes: I can see all the tracks but can't play any of them both by artist and album view.  If I browse the 'Music Library' and look under NAS etc, the I can see the folder, but nothing in the folder.

2. After patch.

Everything works fine :D.  I can see and play everything in whatever browsing view.

No difference in shown numbers of artists, albums and tracks before or after patch.

**Comment by xipmix** [comment]
Good news, thanks for the test.

**Comment by kaito3desuyo** [comment]
@xipmix Thank you for creating the patch. 
Patch worked fine on volumio 2.368.

**Comment by volumio** [comment]
Thanks @xipmix and @kaito3desuyo @chsims1 !

Merging

**Pull request merged**
