### PR TITLE
Musicbrainz

### PR DESCRIPTION
**Pull request by xipmix**
This addresses #1645.

I don't know how to test this aside from uploading the modified file to a running volumio and restarting. I did that, there seemed to be no ill effects.

### CODE REVIEW

**Comment by macmpi** [comment]
Please note some Tags are supported from MPD 0.21.x whereas current Volumio2 uses an older version (0.20.6 or such)...
You may check [MPD release notes](https://github.com/MusicPlayerDaemon/MPD/blob/master/NEWS)

**Comment by xipmix** [comment]
Thanks for mentioning this
```
$ git blame src/tag/Type.h
...
6a9ab8bc0e src/TagType.h     (Max Kellermann   2013-07-30 20:10:24 +0200 56)    TAG_MUSICBRAINZ_ARTISTID,
6a9ab8bc0e src/TagType.h     (Max Kellermann   2013-07-30 20:10:24 +0200 57)    TAG_MUSICBRAINZ_ALBUMID,
6a9ab8bc0e src/TagType.h     (Max Kellermann   2013-07-30 20:10:24 +0200 58)    TAG_MUSICBRAINZ_ALBUMARTISTID,
6a9ab8bc0e src/TagType.h     (Max Kellermann   2013-07-30 20:10:24 +0200 59)    TAG_MUSICBRAINZ_TRACKID,
5525ea45a4 src/tag/TagType.h (Wieland Hoffmann 2014-09-27 18:38:23 +0200 60)    TAG_MUSICBRAINZ_RELEASETRACKID,
42959982a9 src/tag/Type.h    (loujine          2017-12-30 19:05:21 +0000 61)    TAG_MUSICBRAINZ_WORKID,
...
```
So all tag types except the following went into version 0.17.something
 * MUSICBRAINZ_RELEASETRACKID in 0.19
 * MUSICBRAINZ_WORKID in 0.21

I'll add a further commit commenting the ones we are not ready for.

**Comment by volumio** [comment]
But this plugin is not active...

**Comment by xipmix** [comment]
Which is why I asked the OP to explain how he spotted the typo. Ah well. Should I just abandon this?

**Comment by volumio** [comment]
@xipmix  Yes, I think it should be left.

PS: Can you send me an email at info at volumio dot org ?
I have something interesting for you that regards mount utils which is better to be discussed privately

**Pull request merged**
