### PR TITLE
Add ChipDip DACs support

### PR DESCRIPTION
**Pull request by chipdipru**
CHIPDIP Master DAC uses overlay "chipdip-i2s-master-dac" which has already been added to the kernel https://github.com/raspberrypi/linux/blob/rpi-5.10.y/arch/arm/boot/dts/overlays/chipdip-i2s-master-dac-overlay.dts
Both "CHIPDIP Master DAC" and "CHIPDIP Slave DAC" use software "RasGPIOCtrl_v5" for Raspberry GPIO controlling. "RasGPIOCtrl_v5" is started via script "chipdip-dac-init.sh". Both files "chipdip-dac-init.sh" and "RasGPIOCtrl_v5" are placed into the scripts folder.

### CODE REVIEW

**Comment by ashthespy** [comment]
Just a heads up. current Volumio is running on `4.19.yy` kernels, so unless the support has been backported, this isn't going to work as expected.

**Comment by chipdipru** [comment]
> 
> Just a heads up. current Volumio is running on `4.19.yy` kernels, so unless the support has been backported, this isn't going to work as expected.

Thanks for pointing it.

**Comment by chipdipru** [comment]
Overlay "chipdip-i2s-master-dac-overlay.dts" has been added to the rpi-4.19.y kernel by Linux contributors team.
https://github.com/raspberrypi/linux/blob/rpi-4.19.y/arch/arm/boot/dts/overlays/chipdip-i2s-master-dac-overlay.dts

**Comment by chipdipru** [comment]
`#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <bcm2835.h>

static const char NoneString[] = "none";
static const char CloseString[] = "closed";

static const char StatusPlay[] = "play";
static const char StatusStop[] = "stop";

static const char BitDepth_16bit[] = "16";
static const char BitDepth_24bit[] = "24";
static const char BitDepth_32bit[] = "32";

static const char SampleRate_44_1[] = "44100 ";
static const char SampleRate_48[] = "48000 ";
static const char SampleRate_88_2[] = "88200 ";
static const char SampleRate_96[] = "96000 ";
static const char SampleRate_176_4[] = "176400 ";
static const char SampleRate_192[] = "192000 ";

static const char SampleRateField[] = "rate";
static const char BitDepthField[] = "format";


#define RPI_PIN_MUTE              RPI_GPIO_P1_07 //GPIO4 mute
#define RPI_PIN_BD_0              RPI_GPIO_P1_18 //GPIO24 BitDepth bit 0
#define RPI_PIN_BD_1              RPI_GPIO_P1_22 //GPIO25 BitDepth bit 1
#define RPI_PIN_SR_0              RPI_V2_GPIO_P1_29  //GPIO5 SampleRate bit 0
#define RPI_PIN_SR_1              RPI_V2_GPIO_P1_31 //GPIO6 SampleRate bit 1
#define RPI_PIN_SR_2              RPI_V2_GPIO_P1_32 //GPIO12 SampleRate bit 2
#define RPI_PIN_SDWN_EVENT        RPI_V2_GPIO_P1_33 //GPIO13 Shutdown event


#define SAMPLE_RATE_MASK_44_1     0
#define SAMPLE_RATE_MASK_48       (1 << RPI_PIN_SR_0)
#define SAMPLE_RATE_MASK_88_2     ((1 << RPI_PIN_SR_2) | (1 << RPI_PIN_SR_1))
#define SAMPLE_RATE_MASK_96       (1 << RPI_PIN_SR_1)
#define SAMPLE_RATE_MASK_176_4    ((1 << RPI_PIN_SR_2) | (1 << RPI_PIN_SR_1) | (1 << RPI_PIN_SR_0))
#define SAMPLE_RATE_MASK_192      ((1 << RPI_PIN_SR_1) | (1 << RPI_PIN_SR_0))
#define SAMPLE_RATE_MASK          ((1 << RPI_PIN_SR_2) | (1 << RPI_PIN_SR_1) | (1 << RPI_PIN_SR_0))

#define BIT_DEPTH_MASK_16         0
#define BIT_DEPTH_MASK_24         (1 << RPI_PIN_BD_0)
#define BIT_DEPTH_MASK_32         (1 << RPI_PIN_BD_1)
#define BIT_DEPTH_MASK            ((1 << RPI_PIN_BD_1) | (1 << RPI_PIN_BD_0))


#define GPIO_CHANGE_PENDING       1
#define MUTE_ACTIVE               LOW
#define MUTE_NOT_ACTIVE           HIGH



char *GetSampleRate(char *NewState, uint32_t *GPIOMask);
char *GetBitDepth(char *NewState, uint32_t *GPIOMask);


//static char *CurStatus = (char*)NoneString;
static char *CurBitDepth = (char*)NoneString;
static char *CurSampleRate = (char*)NoneString;



//------------------------------------------------------------------------------
int main(int argc, char** argv)
{
	FILE *fp;
	char FileString[100];
	
	if (!bcm2835_init())
      return 1;
	
	bcm2835_gpio_fsel(RPI_PIN_MUTE, BCM2835_GPIO_FSEL_OUTP);
	bcm2835_gpio_write(RPI_PIN_MUTE, MUTE_NOT_ACTIVE); 
	bcm2835_gpio_fsel(RPI_PIN_BD_0, BCM2835_GPIO_FSEL_OUTP);
	bcm2835_gpio_fsel(RPI_PIN_BD_1, BCM2835_GPIO_FSEL_OUTP);
	bcm2835_gpio_fsel(RPI_PIN_SR_0, BCM2835_GPIO_FSEL_OUTP);
	bcm2835_gpio_fsel(RPI_PIN_SR_1, BCM2835_GPIO_FSEL_OUTP);
	bcm2835_gpio_fsel(RPI_PIN_SR_2, BCM2835_GPIO_FSEL_OUTP);
	bcm2835_gpio_fsel(RPI_PIN_SDWN_EVENT, BCM2835_GPIO_FSEL_OUTP);
	bcm2835_gpio_write(RPI_PIN_SDWN_EVENT, HIGH);
	
	//uint16_t i = 0;
	//for(i; i < 100; i++)
	for(;;)
	{
		fp=fopen("/proc/asound/card2/pcm0p/sub0/hw_params", "r");
		if (fp != NULL)
		{
			if (fgets(FileString, 100, fp) != NULL)
			{
				char *CurStatus = strstr(FileString, CloseString);

				if (CurStatus == NULL) //playing
					CurStatus = (char *)StatusPlay;
				else //stop/pause state
					CurStatus = (char *)StatusStop;

				if (strcmp(CurStatus, StatusPlay) == 0)
				{
					uint32_t SampleRateState = 0;
					uint32_t BitDepthState = 0;
					uint8_t GPIOChange = 0;
					char *NewPropertyValue;

					while(fgets(FileString, 50, fp) != NULL)
					{
						if ((strstr(FileString, "subformat") == NULL)
						&&(strstr(FileString, BitDepthField) != NULL))
						{
							NewPropertyValue = GetBitDepth(FileString, &BitDepthState);
							if (strcmp(CurBitDepth, NewPropertyValue) != 0)
							{
								CurBitDepth = NewPropertyValue;
								GPIOChange = GPIO_CHANGE_PENDING;
							}
						}						
						else if (strstr(FileString, SampleRateField) != NULL)
						{
							NewPropertyValue = GetSampleRate(FileString, &SampleRateState);
							if (strcmp(CurSampleRate, NewPropertyValue) != 0)
							{
								CurSampleRate = NewPropertyValue;
								GPIOChange = GPIO_CHANGE_PENDING;
							}
							break;
						} 
					}

					if (GPIOChange == GPIO_CHANGE_PENDING)
					{
						//printf("Something changed...");
						bcm2835_gpio_write(RPI_PIN_MUTE, MUTE_ACTIVE);
						bcm2835_gpio_write_mask(SampleRateState | BitDepthState, SAMPLE_RATE_MASK | BIT_DEPTH_MASK);
						bcm2835_delay(300);
						bcm2835_gpio_write(RPI_PIN_MUTE, MUTE_NOT_ACTIVE);
					}

					//printf("CurStatus is: %s", CurStatus);
					//printf("   CurSampleRate is: %s", CurSampleRate);
					//printf("   CurBitDepth is: %s\n", CurBitDepth);
				}
				//else
					//bcm2835_gpio_write(RPI_PIN_MUTE, MUTE_ACTIVE);
			}

			pclose(fp);
		}
		
		bcm2835_delay(2);
	}
	    
	bcm2835_close();
 
	return 0;
}
//------------------------------------------------------------------------------
char *GetSampleRate(char *NewState, uint32_t *GPIOMask)
{
	char *NewSampleRate = strstr(NewState, SampleRate_44_1);
	if (NewSampleRate != NULL)
	{
		*GPIOMask = SAMPLE_RATE_MASK_44_1;
		return (char *)SampleRate_44_1;
	}
	
	NewSampleRate = strstr(NewState, SampleRate_48);
	if (NewSampleRate != NULL)
	{
		*GPIOMask = SAMPLE_RATE_MASK_48;
		return (char *)SampleRate_48;
	}
	
	NewSampleRate = strstr(NewState, SampleRate_88_2);
	if (NewSampleRate != NULL)
	{
		*GPIOMask = SAMPLE_RATE_MASK_88_2;
		return (char *)SampleRate_88_2;
	}
	
	NewSampleRate = strstr(NewState, SampleRate_96);
	if (NewSampleRate != NULL)
	{
		*GPIOMask = SAMPLE_RATE_MASK_96;
		return (char *)SampleRate_96;
	}
	
	NewSampleRate = strstr(NewState, SampleRate_176_4);
	if (NewSampleRate != NULL)
	{
		*GPIOMask = SAMPLE_RATE_MASK_176_4;
		return (char *)SampleRate_176_4;
	}
	
	*GPIOMask = SAMPLE_RATE_MASK_192;
	return (char *)SampleRate_192;
}
//------------------------------------------------------------------------------
char *GetBitDepth(char *NewState, uint32_t *GPIOMask)
{
	char *NewBitDepth = strstr(NewState, BitDepth_16bit);
	if (NewBitDepth != NULL)
	{
		*GPIOMask = BIT_DEPTH_MASK_16;
		return (char *)BitDepth_16bit;
	}
	
	NewBitDepth = strstr(NewState, BitDepth_24bit);
	if (NewBitDepth != NULL)
	{
		*GPIOMask = BIT_DEPTH_MASK_24;
		return (char *)BitDepth_24bit;
	}
	
	*GPIOMask = BIT_DEPTH_MASK_32;
	return (char *)BitDepth_32bit;
}
`

**Comment by chipdipru** [comment]
Now we recommend to install our DACs via installation script, details https://github.com/chipdipru/Adding-CHIPDIP-DAC-to-Volumio

**Comment by chipdipru** [comment]
We prepared the driver and modified overlay. So the pull request is out of date and will be closed.

**Pull request closed without merging**
