### PR TITLE
Improve discoverShares()

### PR DESCRIPTION
**Pull request by xipmix**
I started looking into #627 and noticed that some shares were not being detected properly by discoverShares(). I've fixed that and hopefully improved the readability somewhat. This has been tested on 2.041 and seems to work correctly.

### CODE REVIEW

**Comment by volumio** [comment]
Pretty clever! (the -N, didn't notice that)
However I am not able to find any share now...

**Comment by xipmix** [comment]
Oh dear. Does the smbtree call work on the command line? If you can send the output I can take a look.

**Comment by volumio** [comment]
Yep, it works:

volumio@volumio:~$ /usr/bin/smbtree -N -b
WORKGROUP
        \\VOLUMIO                       Volumio Audiophile Music Player
                \\VOLUMIO\IPC$                  IPC Service (Volumio Audiophile Music Player)
                \\VOLUMIO\Internal Storage      Volumio Internal Music Folder
        \\FRITZ-NAS                     FRITZ!Box
                \\FRITZ-NAS\IPC$                IPC Service (FRITZ!Box)
                \\FRITZ-NAS\FRITZ.NAS
        \\DISKSTATION
                \\DISKSTATION\IPC$              IPC Service ()
                \\DISKSTATION\video             System default shared folder
                \\DISKSTATION\Torrent
                \\DISKSTATION\Share con spazi
                \\DISKSTATION\Programmi
                \\DISKSTATION\photo             System default shared folder
                \\DISKSTATION\NetBackup         System default shared folder
                \\DISKSTATION\music             System default shared folder
                \\DISKSTATION\Mi
                \\DISKSTATION\IMGs
                \\DISKSTATION\homes             user home
                \\DISKSTATION\FLAC
                \\DISKSTATION\Film
                \\DISKSTATION\Cose Mondo
                \\DISKSTATION\Backup
        \\DESKTOP-HSL3GOL


So I think its a parsing error

**Comment by balbuze** [comment]
Even with 2.0.96 my nas is not always detected. Sometime it's ok, sometime is not. And /usr/bin/smbtree -N -b return nothing in this case, even if nas is already mounted.

**Comment by xipmix** [comment]
Somehow I typoed 'excludednas' as 'excludenas'. This caused an undefined variable exception but I guess since it was inside a try/catch, we ended up in the catch. I've changed the variable name to make it harder to get wrong. For my penance I cut and pasted the updated code into a separate file and ran test cases with your smbtree output and mine, to confirm the parsing worked correctly.

**Comment by volumio** [comment]
Does not work... Now the scan goes OK, but when I hit save it reports "no such address"

**Comment by xipmix** [comment]
Sorry about that. I did some more testing. The shares I had been using to test with happened to have names longer than 16 characters, except the hidden shares. The long names are not padded, but any share names shorter than 16 characters get padded with trailing spaces to be 16 chars long. I wrongly assumed that only hidden shares (which _were_ short names) were padded. I didn't pick this up from your pasted smbtree output because the tabs were lost by the markdown rendering.

So why the failure? The share name gets used as the alias, which in turn is used to construct the mountpoint. The mountpoint is ok because we swap spaces with underscores. For the name of the remote share, the spaces are correctly escaped in addShare but the spaces are not actually part of the share name as defined in smb.conf on the remote host. So the mount fails because we are asking for a share name that does not exist.

Example log:
```
sudo[5374]: volumio : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/bin/mount -t cifs -o guest,ro,dir_mode=0777,file_mode=0666,iocharset=utf8,noauto //UBUNTU/var-tmp         /mnt/NAS/var-tmp________
...
volumio[4939]: exec error Error: Command failed: /usr/bin/sudo /bin/mount -t cifs -o guest,ro,dir_mode=0777,file_mode=0666,iocharset=utf8,noauto //BIGBOX/var-tmp\ \ \ \ \ \ \ \  /mnt/NAS/var-tmp________
volumio[4939]: Retrying with upper case share name
volumio[4939]: mount error(6): No such device or address
volumio[4939]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
volumio[4939]: info: Error mounting  var-tmp         on IP UBUNTU : (6): No such device or address
volumio[4939]: Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
So if we strip the trailing spaces things should work. The number of users with trailing spaces in the real share name is probably zero.

**Comment by volumio** [comment]
Yes that works! And its also quite faster to mount, well done!

**Pull request merged**
