### PR TITLE
Fix undefined when adding a playlist of radios to the queue

### PR DESCRIPTION
**Pull request by marius-hi**
When adding a playlist of radios to a queue using the options "Play" or "Add to queue", their name appear in the queue as undefined instead of keeping the original name:

undefined

This commit fixes the issue.

### CODE REVIEW

**Comment by xipmix** [comment]
I'm curious - why the name change from 'uris' to 'array' ?

Also I'm not sure about the change at line 179 - I agree it is more consistent to use 'title' in that data structure but there are other places where a 'name' field is used that might also need to be changed e.g.  https://github.com/volumio/Volumio2/blob/b78ecf1a48254ce8eadcc4803b4fff49030ca2e5/app/playlistManager.js#L297-L346

**Comment by xipmix** [comment]
Could you attach an example playlist of webradios to this issue please - would make testing easier.

**Comment by marius-hi** [comment]
Thanks for suggestion @xipmix . I updated my PR.
The change at the line 179 is not about consistency. That line fixes the names when adding the playlist to queue.

Here is an example of playlist:
`[{"service":"webradio","uri":"http://media-the.musicradio.com/CapitalMP3","title":"Capital London","albumart":"/albumart"},
{"service":"webradio","uri":"http://streaming.hotmixradio.fr/hotmixradio-dance-64.mp3","title":"Hotmixradio Dance France","albumart":"/albumart"},
{"service":"webradio","uri":"http://209.85.88.199:10040/;","title":"The JOY FM","albumart":"/albumart"}]`

**Comment by volumio** [comment]
Also, you changed name to title. Which will make tracks name undefined. Please use a conditional  that handles the title or name usage

**Comment by xipmix** [comment]
I was able to reproduce this with VOLUMIO_VERSION="2.657" on pi2.

I can create a playlist of webradios by adding a couple from the Top500 to the queue and then saving that. The file looks like this:
```
[{"service":"webradio",
   "uri":"http://yp.shoutcast.com/sbin/tunein-station.m3u?id=1219771",
   "title":"CALM RADIO - SOLO PIANO",
   "albumart":"/albumart"},
 {"service":"webradio",
   "uri":"http://yp.shoutcast.com/sbin/tunein-station.m3u?id=1735956","
    title":"COOLfahrenheit 93 - (7)",
    "albumart":"/albumart"},
  {"service":"webradio",
    "uri":"http://yp.shoutcast.com/sbin/tunein-station.m3u?id=1316460",
    "title":"Ok Radio High bandwidth 128k stereo server EU",
    "albumart":"/albumart"}]
```
When I add the webradios to the queue initially, they display fine. But when I clear the queue and add the playlist to the queue, I get the 'undefined' rendering in the same way. I see the same behaviour with your playlist file.

**Comment by xipmix** [comment]
I found that this patch resolves the issue for me, but maybe it's kind of a dumb way to do it.

@volumio, why is there this apparent inconsistency between ```name:``` and ```title:``` fields ?
It's unclear to me why the ```name:``` field is needed at all for queueable items.

```
--- a/app/playlistManager.js
+++ b/app/playlistManager.js
@@ -177,6 +177,7 @@ PlaylistManager.prototype.enqueue = function (name) {
                             service: data[i].service,
                             uri: data[i].uri,
                             name: data[i].title,
+                            title: data[i].title,
                             artist: data[i].artist,
                             album: data[i].album,
                             albumart: data[i].albumart
@@ -307,7 +308,7 @@ PlaylistManager.prototype.addToMyWebRadio = function (service, radio_name, uri)
        fs.exists(filePath, function (exists) {
            var fileDefer;
                if (!exists) {
-            playlist.push({service: service, name: radio_name, uri: uri});
+            playlist.push({service: service, name: radio_name, title: radio_name, uri: uri});
             fileDefer=self.saveJSONFile(folder, name, playlist);
                } else fileDefer=libQ.resolve();
 
@@ -327,7 +328,7 @@ PlaylistManager.prototype.addToMyWebRadio = function (service, radio_name, uri)
                     }
 
                     if (alreadyExists == false) {
-                        data.push({service: service, name: radio_name, uri: uri});
+                        data.push({service: service, name: radio_name, title: radio_name, uri: uri});
                     }
 
                     self.saveJSONFile(folder, name, data).then(function(){
```

**Comment by xipmix** [comment]
So after reading through the app/*.js files that mention a ```name:``` or       ```title:``` data field it would seem that:
 * items in the playback queue are expected to have the ```name:``` field and   not ```title:```
 * items in playlist files are expected to have ```title:``` and not ```name:```
                                                                                
However                                                                         
 * items in the 'my-web-radio' playlist are expected to have ```name:``` but    not ```title:```, e.g. the ```addToMyWebRadio``` function linked above.

I tried a more minimal change (below) but got 'undefined' in the play queue listing.
So it seems _both_ fields are required for web radios, to avoid this issue. Maybe there
is a mistake somewhere in how the play queue items are being displayed in the webradio case.
```
diff --git a/app/playlistManager.js b/app/playlistManager.js                    
index 094136d..344d1b4 100755                                                   
--- a/app/playlistManager.js                                                    
+++ b/app/playlistManager.js                                                    
@@ -307,7 +307,7 @@ PlaylistManager.prototype.addToMyWebRadio = function        (service, radio_name, uri)
        fs.exists(filePath, function (exists) {                                 
            var fileDefer;                                                      
                if (!exists) {                                                  
-            playlist.push({service: service, name: radio_name, uri: uri});     
+            playlist.push({service: service, title: radio_name, uri: uri});    
             fileDefer=self.saveJSONFile(folder, name, playlist);               
                } else fileDefer=libQ.resolve();                                
                                                                                
@@ -320,14 +320,14 @@ PlaylistManager.prototype.addToMyWebRadio = function      (service, radio_name, uri)
                     var alreadyExists = false;                                 
                                                                                
                     for (var i in data) {                                      
-                        if (data[i].name == radio_name) {                      
+                        if (data[i].title == radio_name) {                     
                             alreadyExists = true;                              
                             data[i].uri = uri;                                 
                         }                                                      
                     }                                                          
                                                                                
                     if (alreadyExists == false) {                              
-                        data.push({service: service, name: radio_name, uri:    uri});
+                        data.push({service: service, title: radio_name, uri:   uri});
                     }                                                          
                                                                                
                     self.saveJSONFile(folder, name, data).then(function(){     
@@ -366,7 +366,7 @@ PlaylistManager.prototype.removeFromMyWebRadio = function   (name, service, uri) {
                        else {                                                  
                                //searching for item with same name             
                                for (var i in data) {                           
-                                       if (data[i].name == name) {             
+                                       if (data[i].title == name) {            
                                                data.splice(i, 1);              
                                        }                                       
                                }                                               
```

**Comment by xipmix** [comment]
Ok I think I have it now.

Things only go wrong when a webradio stored in a playlist is added to the queue.
Here's the sequence of events with a little extra debug.
```
2019-10-24T10:30:27.269Z - info: Enqueue extra2                                 
2019-10-24T10:30:27.278Z - info: Enqueue data[0].title Hitradio OE3             
2019-10-24T10:30:27.279Z - info: Enqueue data[0].name undefined                 
2019-10-24T10:30:27.281Z - info: CoreCommandRouter::volumioAddQueueItems        
2019-10-24T10:30:27.283Z - info: CoreStateMachine::addQueueItems                
2019-10-24T10:30:27.286Z - info: CorePlayQueue::addQueueItems                   
2019-10-24T10:30:27.287Z - info: Adding Item to queue: http://yp.shoutcast.com/sbin/tunein-     station.m3u?id=1826116
2019-10-24T10:30:27.288Z - info: webradio with title: undefined name: Hitradio OE3
2019-10-24T10:30:27.288Z - info: CoreCommandRouter::executeOnPlugin: webradio , explodeUri
2019-10-24T10:30:27.297Z - info: CorePlayQueue::saveQueue                       
2019-10-24T10:30:27.299Z - info: CoreCommandRouter::volumioPushQueue            
2019-10-24T10:30:27.308Z - info: CoreStateMachine::updateTrackBlock             
2019-10-24T10:30:27.310Z - info: CorePlayQueue::getTrackBlock                   
```
The playlist file looks like this:
```
[{"service":"webradio",                                                         
  "uri":"http://yp.shoutcast.com/sbin/tunein-station.m3u?id=1826116",           
  "title":"Hitradio OE3",                                                       
  "albumart":"https://i3.radionomy.com/radios/200/6/6f2c/6f2ca76b-4d1d-464d-a336-db0913fb5229.  jpg"}]
```

The data format on disk is correct, and enqueue() sets the ```name:``` field for the queue item using the ```title:``` field from the playlist file.
Where things fall over is in that ```explodeUri``` call. We end up here
https://github.com/volumio/Volumio2/blob/0b9279fa6125327588395bccaddba81cda50df4b/app/plugins/music_service/webradio/index.js#L614-L618

i.e. data.title is undefined and used to overwrite the data.name field.

See #1821

**Comment by jwoodard80** [comment]
Not sure if I need to tag onto this or not, however, when adding a playlist VIA api with a web radio inside I have the same issue and it shows "undefined"

**Comment by xipmix** [comment]
Thanks for that. If you apply the patch does it help? (it's a one-line change)

**Comment by jwoodard80** [comment]
So forgive my ignorance.... how do i do this? I thought I could just change the file, however, it is not changing when I restart the device. the static directory still contains the old lines. 

Happy to do it if someone could provide steps and locations to change.

**Comment by xipmix** [comment]
What I was thinking you would do was
 * ssh into your volumio 
 * edit ```/volumio/ app/plugins/music_service/webradio/index.js``` 
 * ```systemctl restart volumio``` (or just reboot the device)

which sounds like what you did. I'm not sure I understand 'the static directory still contains the old lines'. What's the path to that static directory?

**Comment by volumio** [comment]
Superseeded by https://github.com/volumio/Volumio2/pull/1821

**Pull request closed without merging**
