### PR TITLE
Added GNU3 license

### PR DESCRIPTION
**Pull request by nickcannariato**
Noticed that the website had the license posted, but the repo didn't. Added the matching license to the repo.

### CODE REVIEW

**Comment by volumio** [comment]
I'm delaying the decision on the Licence, since I'm not sure to stick with it or change to MIT or others. Open for suggestions

**Comment by nickcannariato** [comment]
I'm personally a big fan of MIT because it's the simplest and most permissive (outside of The Unlicense, which carries no requirements at all). GNU is fairly stringent by comparison and is meant to keep the source code open. 

I guess ultimately it depends on whether/how you would like independent or commercial developers to use the source code in their own projects, should desire to do that at all. Thoughts?

**Comment by jomo** [comment]
IANAL, but I think you need every [contributor](https://github.com/volumio/Volumio2/graphs/contributors) to agree on license changes. I'm not sure how the legal situation is when no License was present and a new one is added, but I guess the same would apply.

> I'm not sure to stick with it or change to MIT or others

I prefer MIT for most of my own projects but I'd be happy with any [Open Source License](https://opensource.org/licenses) as well.

**Comment by volumio** [comment]
An open discussion with volumio's community  is here
https://volumio.org/forum/volumio2-licence-change-t3522.html

**Comment by volumio** [comment]
I think we can go with GPLv3 for the system. Any contributor which doesn't agree please let us know, not telling anything before the licence change will imply agreeing on this

**Comment by philkunz** [comment]
any updates here?

**Comment by apinner** [comment]
@volumio are we any closer to choosing a license?

**Pull request merged**
